apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yn18e95cl-python 
  janus-idp.io/tekton: yn18e95cl-python
  backstage.io/kubernetes-id: yn18e95cl-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yn18e95cl-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml