apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yn18e95cl-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yn18e95cl-python 
  name: yn18e95cl-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yn18e95cl-python 
